### ISSUE TITLE
Revamp application home page

### ISSUE THREAD

**Issue by biswain2309** [biswain2309/articlyzer-project#18]
Currently Articlyzer doesn't have theme or specific design system. Try to come up with some designs for the landing page. It should cover the navbar, background, Textbox, Input Box and buttons.

**Comment by biswain2309** [comment]
@sprakash57 I can see you have made changes to `home.html`. Would you mind taking care of this one as well? It is mostly style changes. Any ideas would be welcome.

**Comment by sprakash57** [comment]
Sure. I will give it a try.

**Comment by sprakash57** [comment]
I have raised #25 that will take care of it. However, there is some issue with the footer section. I can see there is a separate issue #20. Maybe we can take care of it there.
