### ISSUE TITLE
Copyright symbol is overlapping with footer content.

### ISSUE THREAD

**Issue by biswain2309** [biswain2309/articlyzer-project#20]
On mobile devices, the copyright symbol overlaps with footer content. It should not overlap with any of the main content.

**Comment by biswain2309** [comment]
@sprakash57 Hey, I have noticed an issue if you directly access `/a` routes. It throws error. Would you mind taking care both of them in this issue?

**Comment by sprakash57** [comment]
Sure 😊

**Comment by sprakash57** [comment]
#27 is ready for review.
